// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtwzhnjmymuvyxyvqkjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0d3pobmpteW11dnl4eXZxa2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTg1NDMsImV4cCI6MjA1NDU5NDU0M30.yqjj8A12557BYTVVswVJqJFAyt1mR9j_qCA7k7uEUtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);